### PR TITLE
fix unrecognized command error

### PR DESCRIPTION
**Pull request by aniketmaurya**
this PR adds repo_id arg to fix the error:

`download.py: error: Unrecognized arguments: togethercomputer/RedPajama-INCITE-Base-3B-v1`

### CODE REVIEW

**Review by lantiga — APPROVED** [review]
Thank you @aniketmaurya !

**Comment by lantiga** [comment]
Actually @aniketmaurya can you also address this the other howtos?

**Comment by lantiga** [comment]
For visibility: #44

**Comment by aniketmaurya** [comment]
> Actually @aniketmaurya can you also address this the other howtos?

yes @lantiga, I will address the other howtos as well

**Pull request merged**
