### PR TITLE
Support Falcon 40B

### PR DESCRIPTION
**Pull request by carmocca**
40B has some architectural differences, most importantly, uses grouped-query attention (GQA)

**Design decision:**
Since GQA is a generalization of MQA and MHA, we don't need separate code paths. This makes the code very tidy and nice. On the other hand, we might prefer separating the MQA, MHA, and GQA code paths to make it easier to grasp.
See https://github.com/Lightning-AI/lit-parrot/pull/102/commits/fbf367351e80593950e3bed01038d9646e5c5317 for the difference.

### CODE REVIEW

**Comment by lantiga** [comment]
Very cool, we should write a succinct note in the code about MHA, MQA and GQA

And it would make a great blog post BTW @rasbt

**Review by carmocca — COMMENTED** [review]
This is now ready.

I haven't run the 40b model because it doesn't fit on an A100. I want to try it with gpt4 quantization but that will take me some time.
I added a test to check numerical parity though.

Adding that comment

**Review by lantiga — APPROVED** [review]
Looks great, remember to update the Falcon howto!

To run the 40B I propose:
- we get the bitsandbytes new 4bit in
- we look into parallel layers from `fairscale`

**Comment by carmocca** [comment]
@lantiga I did update the falcon howto. Is there something else you had in mind?

**Comment by rasbt** [comment]
> Very cool, we should write a succinct note in the code about MHA, MQA and GQA
> 
> And it would make a great blog post BTW @rasbt :-)
> 
> I find the generalized formulation super clean, we just need to add a good comment

Yes, that's a very exciting topic! Adding it to my neverending list, haha

**Pull request merged**
