### PR TITLE
Fixed codec errors in prepare_alpaca script

### PR DESCRIPTION
**Pull request by gmongaras**
Small edit to scripts/prepare_alpaca.py to fix codec errors I ran into when finetuning for Falcon.

### CODE REVIEW

**Comment by carmocca** [comment]
Python should be choosing the correct encoding by default: https://stackoverflow.com/a/36316351

Are you perhaps using Windows?

**Comment by gmongaras** [comment]
Yep, I'm using windows. It works perfectly fine on my linux device, but had to add the encoding param to get it to work on my windows machine.

**Comment by carmocca** [comment]
There's several other places that use `open()` without encoding:

```python
chat/base.py:120:    with open(checkpoint_dir / "lit_config.json") as fp:
finetune/adapter.py:107:    with open(data_dir / "config.json") as data_config_path:
finetune/lora.py:108:    with open(data_dir / "config.json") as data_config_path:
finetune/adapter_v2.py:113:    with open(data_dir / "config.json") as data_config_path:
generate/base.py:131:    with open(checkpoint_dir / "lit_config.json") as fp:
generate/adapter.py:67:    with open(checkpoint_dir / "lit_config.json") as fp:
generate/lora.py:73:    with open(checkpoint_dir / "lit_config.json") as fp:
generate/adapter_v2.py:69:    with open(checkpoint_dir / "lit_config.json") as fp:
lit_parrot/tokenizer.py:13:        with open(config_path) as fp:
lit_parrot/utils.py:420:        with self._fs.open(self.metrics_file_path, "w", newline="") as f:
lit_parrot/packed_dataset.py:102:        with open(filename, "wb") as f:
lit_parrot/packed_dataset.py:167:        with open(path, "rb") as f:
quantize/gptq.py:334:    with open(checkpoint_dir / "lit_config.json") as fp:
scripts/prepare_alpaca.py:43:    with open(checkpoint_dir / "lit_config.json", "r") as file:
scripts/prepare_alpaca.py:51:    with open(data_file_path, "r") as file:
scripts/prepare_alpaca.py:93:    with open(destination_path / "config.json", "w") as file:
scripts/prepare_alpaca.py:101:    with open(file_path, "w") as f:
scripts/convert_hf_checkpoint.py:126:    with open(checkpoint_dir / "lit_config.json", "w") as json_config:
scripts/convert_hf_checkpoint.py:141:        with open(pytorch_bin_map_json_path) as json_map:
scripts/prepare_redpajama.py:151:    with open(checkpoint_dir / "lit_config.json") as fp:
```

Why do those not fail? Or have you not run any of the rest? Do they need an update too?

Sorry for my basic question, I'm not very experienced with Windows

**Comment by gmongaras** [comment]
I tried out a few and it looks like it works fine without the utf-8 encoding explicitly defined. I think the problem comes from strange characters in a dataset with raw text data that the config files don't have. I haven't used PackedDataset in `lit_parrot/packed_dataset.py`, but I'm guessing it may also require the utf-8 encoding argument since it looks like it deals with raw data.

**Comment by carmocca** [comment]
Good call, then let's update that script too

**Pull request merged**
